// GRE Study Machine — vocabulary deck (high-frequency GRE words)
// Format: {word, pos, def, ex}
var GRE_VOCAB = [
  {word:"Abate", pos:"v.", def:"to reduce in intensity or degree; subside", ex:"The storm abated by morning, leaving calm seas."},
  {word:"Abeyance", pos:"n.", def:"temporary suspension or inactivity", ex:"The plan was held in abeyance until funding arrived."},
  {word:"Abscond", pos:"v.", def:"to leave secretly, esp. to avoid arrest or debt", ex:"The embezzler absconded with the company's reserves."},
  {word:"Acquiesce", pos:"v.", def:"to accept or comply passively; give in", ex:"He acquiesced to the committee's demands rather than fight them."},
  {word:"Acrid", pos:"adj.", def:"sharp or bitter in smell/taste; harsh", ex:"The acrid smoke forced everyone outdoors."},
  {word:"Alacrity", pos:"n.", def:"eager willingness; promptness", ex:"She accepted the internship with alacrity."},
  {word:"Ambiguous", pos:"adj.", def:"open to more than one interpretation", ex:"The ambiguous clause sparked a lawsuit."},
  {word:"Ameliorate", pos:"v.", def:"to make better; improve", ex:"New policies ameliorated working conditions."},
  {word:"Anomaly", pos:"n.", def:"something that deviates from the norm", ex:"The spike in sales was an anomaly, not a trend."},
  {word:"Apathy", pos:"n.", def:"lack of interest or concern", ex:"Voter apathy doomed the referendum."},
  {word:"Arbitrary", pos:"adj.", def:"based on whim, not reason or system", ex:"The arbitrary ruling angered both sides."},
  {word:"Ascetic", pos:"adj.", def:"practicing self-denial; austere", ex:"The ascetic monk owned almost nothing."},
  {word:"Austere", pos:"adj.", def:"severe or strict in manner; plain", ex:"The monastery's austere walls offered no comfort."},
  {word:"Banal", pos:"adj.", def:"lacking originality; trite", ex:"The banal plot bored sophisticated viewers."},
  {word:"Bellicose", pos:"adj.", def:"demonstrating aggression; warlike", ex:"His bellicose rhetoric alarmed diplomats."},
  {word:"Benevolent", pos:"adj.", def:"well-meaning; kindly", ex:"The benevolent donor funded the clinic."},
  {word:"Capitulate", pos:"v.", def:"to surrender; give up resistance", ex:"After months of siege, the city capitulated."},
  {word:"Carp", pos:"v.", def:"to complain pettily; find fault", ex:"She carped about the slightest errors."},
  {word:"Castigate", pos:"v.", def:"to criticize severely", ex:"The editorial castigated the mayor's inaction."},
  {word:"Cogent", pos:"adj.", def:"clear, logical, and convincing", ex:"She made a cogent argument for the reform."},
  {word:"Commensurate", pos:"adj.", def:"corresponding in size or degree", ex:"Pay should be commensurate with experience."},
  {word:"Complaisant", pos:"adj.", def:"eager to please; agreeable", ex:"The complaisant assistant nodded at everything."},
  {word:"Contentious", pos:"adj.", def:"causing disagreement; quarrelsome", ex:"The contentious clause stalled negotiations."},
  {word:"Contrite", pos:"adj.", def:"feeling remorseful", ex:"His contrite apology was accepted."},
  {word:"Convoluted", pos:"adj.", def:"extremely complex; intricate", ex:"The convoluted tax code needs reform."},
  {word:"Credulous", pos:"adj.", def:"too ready to believe; gullible", ex:"Credulous investors bought the scam."},
  {word:"Deleterious", pos:"adj.", def:"causing harm or damage", ex:"The deleterious effects of pollution are clear."},
  {word:"Demagogue", pos:"n.", def:"leader who appeals to emotions, not reason", ex:"The demagogue exploited public fears."},
  {word:"Deride", pos:"v.", def:"to mock or ridicule", ex:"Critics derided the film as shallow."},
  {word:"Desiccated", pos:"adj.", def:"dried out; deprived of moisture", ex:"The desiccated soil cracked in the heat."},
  {word:"Diatribe", pos:"n.", def:"a bitter verbal attack", ex:"He launched a diatribe against the policy."},
  {word:"Diffident", pos:"adj.", def:"modest; lacking self-confidence", ex:"The diffident student rarely spoke up."},
  {word:"Disparage", pos:"v.", def:"to speak of slightingly; belittle", ex:"Critics disparaged the film, though audiences loved it."},
  {word:"Dissemble", pos:"v.", def:"to conceal feelings; disguise", ex:"He dissembled his true motives."},
  {word:"Dogmatic", pos:"adj.", def:"stubbornly adhering to beliefs", ex:"Her dogmatic refusal to compromise stalled talks."},
  {word:"Ebullient", pos:"adj.", def:"overflowing with enthusiasm", ex:"The ebullient crowd celebrated the win."},
  {word:"Eclectic", pos:"adj.", def:"drawing from varied sources", ex:"The museum's eclectic collection spans eras."},
  {word:"Efficacy", pos:"n.", def:"the ability to produce a desired effect", ex:"The efficacy of the drug was proven."},
  {word:"Elegy", pos:"n.", def:"a mournful poem or song", ex:"He wrote an elegy for the fallen soldiers."},
  {word:"Equivocate", pos:"v.", def:"to use ambiguous language to conceal truth", ex:"The senator equivocated when asked about the scandal."},
  {word:"Erudite", pos:"adj.", def:"having great knowledge; scholarly", ex:"The erudite professor cited obscure sources."},
  {word:"Exacerbate", pos:"v.", def:"to make worse", ex:"The new policy exacerbated the housing shortage."},
  {word:"Exculpate", pos:"v.", def:"to free from blame", ex:"New evidence exculpated the suspect."},
  {word:"Exigent", pos:"adj.", def:"demanding immediate action; urgent", ex:"The exigent crisis required swift response."},
  {word:"Facetious", pos:"adj.", def:"treating serious things lightly", ex:"His facetious remark drew glares."},
  {word:"Fallacious", pos:"adj.", def:"based on a false idea; misleading", ex:"The fallacious argument collapsed under scrutiny."},
  {word:"Fastidious", pos:"adj.", def:"very attentive to detail; hard to please", ex:"He was fastidious about report formatting."},
  {word:"Fatuous", pos:"adj.", def:"silly and pointless", ex:"Her fatuous comment ended the debate."},
  {word:"Garrulous", pos:"adj.", def:"excessively talkative", ex:"The garrulous passenger talked the whole flight."},
  {word:"Gregarious", pos:"adj.", def:"fond of company; sociable", ex:"The gregarious host thrived at parties."},
  {word:"Guile", pos:"n.", def:"sly cunning; deceit", ex:"He used guile to win the negotiation."},
  {word:"Hubris", pos:"n.", def:"excessive pride or self-confidence", ex:"His hubris led him to ignore the warnings."},
  {word:"Iconoclast", pos:"n.", def:"one who attacks established beliefs", ex:"The iconoclast challenged the dogma."},
  {word:"Impecunious", pos:"adj.", def:"having little money", ex:"The impecunious student worked two jobs."},
  {word:"Innocuous", pos:"adj.", def:"harmless; not likely to offend", ex:"The comment seemed innocuous at the time."},
  {word:"Insidious", pos:"adj.", def:"proceeding harmfully in a subtle way", ex:"The insidious pathogen spread undetected for weeks."},
  {word:"Intransigent", pos:"adj.", def:"refusing to compromise", ex:"The intransigent union rejected the offer."},
  {word:"Inundate", pos:"v.", def:"to overwhelm; flood", ex:"The office was inundated with applications."},
  {word:"Irascible", pos:"adj.", def:"easily angered", ex:"His irascible temper cost him friends."},
  {word:"Laconic", pos:"adj.", def:"using few words; terse", ex:"His laconic reply revealed little."},
  {word:"Lassitude", pos:"n.", def:"a state of fatigue; lack of energy", ex:"The heat induced a pleasant lassitude."},
  {word:"Loquacious", pos:"adj.", def:"talkative; garrulous", ex:"The loquacious host kept conversation flowing."},
  {word:"Maudlin", pos:"adj.", def:"self-pityingly emotional", ex:"The maudlin speech made viewers uneasy."},
  {word:"Mendacious", pos:"adj.", def:"untruthful; lying", ex:"The mendacious witness was discredited."},
  {word:"Meticulous", pos:"adj.", def:"showing great attention to detail", ex:"She kept meticulous records of every transaction."},
  {word:"Mollify", pos:"v.", def:"to soothe; reduce anger", ex:"He tried to mollify the upset client."},
  {word:"Morose", pos:"adj.", def:"sullen; gloomy", ex:"His morose mood darkened the room."},
  {word:"Nuance", pos:"n.", def:"a subtle distinction", ex:"She appreciated the nuance in his argument."},
  {word:"Obdurate", pos:"adj.", def:"stubborn; unyielding", ex:"The obdurate judge refused the appeal."},
  {word:"Obsequious", pos:"adj.", def:"excessively eager to please; servile", ex:"The obsequious assistant agreed with everything."},
  {word:"Obfuscate", pos:"v.", def:"to deliberately make unclear", ex:"The report obfuscated the real costs."},
  {word:"Onerous", pos:"adj.", def:"burdensome; difficult", ex:"The onerous task took all weekend."},
  {word:"Ostensible", pos:"adj.", def:"stated but not necessarily true", ex:"His ostensible reason was a lie."},
  {word:"Palliative", pos:"n./adj.", def:"something that relieves without curing", ex:"The drug was a palliative, not a cure."},
  {word:"Pellucid", pos:"adj.", def:"translucently clear; easy to understand", ex:"The pellucid stream revealed every stone below."},
  {word:"Pernicious", pos:"adj.", def:"harmful, esp. gradually", ex:"The pernicious myth discouraged investment."},
  {word:"Pervasive", pos:"adj.", def:"spreading throughout", ex:"The pervasive smell of smoke lingered."},
  {word:"Petulant", pos:"adj.", def:"childishly irritable", ex:"The petulant child refused to eat."},
  {word:"Placate", pos:"v.", def:"to pacify; calm", ex:"They raised pay to placate workers."},
  {word:"Pragmatic", pos:"adj.", def:"practical; results-oriented", ex:"A pragmatic approach solved the outage quickly."},
  {word:"Precipitate", pos:"v./adj.", def:"to cause suddenly; hasty", ex:"The comments precipitated a crisis."},
  {word:"Puerile", pos:"adj.", def:"immature; childish", ex:"His puerile jokes fell flat."},
  {word:"Pugnacious", pos:"adj.", def:"eager to fight; aggressive", ex:"The pugnacious debater attacked every point."},
  {word:"Quixotic", pos:"adj.", def:"extremely idealistic; impractical", ex:"His quixotic plan to end all war won no funding."},
  {word:"Recalcitrant", pos:"adj.", def:"stubbornly resistant to authority", ex:"The recalcitrant mule refused to move."},
  {word:"Redoubtable", pos:"adj.", def:"formidable; commanding respect", ex:"The redoubtable general won every battle."},
  {word:"Reticent", pos:"adj.", def:"reserved; disinclined to speak", ex:"She was reticent about her past."},
  {word:"Sanguine", pos:"adj.", def:"optimistic, esp. in difficulty", ex:"She remained sanguine about the startup's prospects."},
  {word:"Soporific", pos:"adj.", def:"sleep-inducing", ex:"The soporific lecture emptied the room."},
  {word:"Sporadic", pos:"adj.", def:"occurring at irregular intervals", ex:"Sporadic protests broke out over the summer."},
  {word:"Strident", pos:"adj.", def:"loud, harsh, and insistent", ex:"The strident tone of the debate alienated voters."},
  {word:"Tacit", pos:"adj.", def:"understood without being stated", ex:"They had a tacit agreement not to compete."},
  {word:"Taciturn", pos:"adj.", def:"reserved; saying little", ex:"The taciturn farmer spoke only when necessary."},
  {word:"Tractable", pos:"adj.", def:"easily managed or controlled", ex:"The tractable algorithm converged in seconds."},
  {word:"Ubiquitous", pos:"adj.", def:"present everywhere", ex:"Smartphones are now ubiquitous."},
  {word:"Undulate", pos:"v.", def:"to move in waves", ex:"The wheat fields undulated in the wind."},
  {word:"Vex", pos:"v.", def:"to annoy or frustrate", ex:"The repeated delays vexed the travelers."},
  {word:"Vilify", pos:"v.", def:"to speak evil of; defame", ex:"The press vilified the official."},
  {word:"Vociferous", pos:"adj.", def:"loud and forceful in expression", ex:"Vociferous critics demanded the CEO resign."},
  {word:"Volatile", pos:"adj.", def:"liable to change rapidly; unstable", ex:"The volatile market swung daily."},
  {word:"Wily", pos:"adj.", def:"skilled at gaining advantage; cunning", ex:"The wily negotiator secured the better deal."},
  {word:"Winsome", pos:"adj.", def:"attractive in a charming way", ex:"Her winsome smile won the room."},
  {word:"Zealous", pos:"adj.", def:"filled with eager enthusiasm; fervent", ex:"The zealous volunteer worked through the night."},
  {word:"Abstemious", pos:"adj.", def:"restraining from indulgence", ex:"His abstemious diet surprised guests."},
  {word:"Acrimony", pos:"n.", def:"bitter hatred; animosity", ex:"The divorce was marked by acrimony."},
  {word:"Adamant", pos:"adj.", def:"refusing to be persuaded", ex:"She was adamant about the deadline."},
  {word:"Apprise", pos:"v.", def:"to inform; notify", ex:"Please apprise me of any changes."},
  {word:"Assuage", pos:"v.", def:"to make less severe; ease", ex:"The apology assuaged her anger."},
  {word:"Audacious", pos:"adj.", def:"bold; daring", ex:"The audacious plan stunned investors."},
  {word:"Candor", pos:"n.", def:"honesty; frankness", ex:"He spoke with refreshing candor."},
  {word:"Caustic", pos:"adj.", def:"sarcastic; biting", ex:"Her caustic wit cut through the flattery."},
  {word:"Chicanery", pos:"n.", def:"trickery; deception", ex:"The contract was full of chicanery."},
  {word:"Circumspect", pos:"adj.", def:"cautious; prudent", ex:"He was circumspect with his finances."},
  {word:"Copious", pos:"adj.", def:"abundant; plentiful", ex:"She took copious notes."},
  {word:"Culpable", pos:"adj.", def:"deserving blame", ex:"The culprit was held culpable."},
  {word:"Deference", pos:"n.", def:"respectful submission", ex:"He spoke with deference to his mentor."},
  {word:"Dilatory", pos:"adj.", def:"slow to act; tardy", ex:"The dilatory committee missed the deadline."},
  {word:"Discerning", pos:"adj.", def:"showing good judgment", ex:"A discerning eye caught the forgery."},
  {word:"Ebullience", pos:"n.", def:"zest; enthusiasm", ex:"Her ebullience energized the team."},
  {word:"Elicit", pos:"v.", def:"to draw out; evoke", ex:"The question elicited frank answers."},
  {word:"Embellish", pos:"v.", def:"to decorate; add false detail", ex:"He embellished the story with lies."},
  {word:"Equanimity", pos:"n.", def:"calmness under stress", ex:"She faced the news with equanimity."},
  {word:"Exonerate", pos:"v.", def:"to free from blame", ex:"The alibi exonerated him."},
  {word:"Florid", pos:"adj.", def:"flowery; excessively decorated", ex:"His florid prose weary readers."},
  {word:"Fortuitous", pos:"adj.", def:"happening by lucky chance", ex:"A fortuitous meeting led to the job."},
  {word:"Frugal", pos:"adj.", def:"economical; sparing", ex:"Her frugal habits built savings."},
  {word:"Glib", pos:"adj.", def:"fluent but insincere", ex:"His glib promises meant nothing."},
  {word:"Grandiose", pos:"adj.", def:"impressive but impractical", ex:"The grandiose scheme collapsed."},
  {word:"Hackneyed", pos:"adj.", def:"overused; clichéd", ex:"The hackneyed phrase drew groans."},
  {word:"Halcyon", pos:"adj.", def:"calm; peaceful", ex:"They remembered halcyon childhood summers."},
  {word:"Iconoclastic", pos:"adj.", def:"attacking cherished beliefs", ex:"Her iconoclastic views stirred debate."},
  {word:"Impassive", pos:"adj.", def:"showing no emotion", ex:"The impassive guard revealed nothing."},
  {word:"Imperturbable", pos:"adj.", def:"calm; unshakable", ex:"Her imperturbable manner soothed clients."},
  {word:"Inchoate", pos:"adj.", def:"just begun; undeveloped", ex:"The inchoate plan needed work."},
  {word:"Ineffable", pos:"adj.", def:"too great to express", ex:"The view was ineffable."},
  {word:"Insouciant", pos:"adj.", def:"carefree; unconcerned", ex:"Her insouciant attitude baffled him."},
  {word:"Lugubrious", pos:"adj.", def:"mournful; gloomy", ex:"His lugubrious expression suited the dirge."},
  {word:"Mellifluous", pos:"adj.", def:"sweetly flowing (sound)", ex:"Her mellifluous voice calmed the room."},
  {word:"Munificent", pos:"adj.", def:"very generous", ex:"The munificent gift funded the library."},
  {word:"Obviate", pos:"v.", def:"to remove the need for", ex:"The prepayment obviated further bills."},
  {word:"Paean", pos:"n.", def:"a song of praise", ex:"The speech was a paean to freedom."},
  {word:"Paradigm", pos:"n.", def:"a model or pattern", ex:"The discovery shifted the scientific paradigm."},
  {word:"Pariah", pos:"n.", def:"an outcast", ex:"After the scandal he became a pariah."},
  {word:"Pell-mell", pos:"adv.", def:"in disorderly haste", ex:"They fled pell-mell from the fire."},
  {word:"Piquant", pos:"adj.", def:"pleasantly sharp; stimulating", ex:"The piquant sauce woke the palate."},
  {word:"Platitude", pos:"n.", def:"a trite remark", ex:"He offered only platitudes."},
  {word:"Precipitous", pos:"adj.", def:"steep; abrupt", ex:"The precipitous drop in sales alarmed them."},
  {word:"Pristine", pos:"adj.", def:"in original condition", ex:"The pristine manuscript survived centuries."},
  {word:"Proclivity", pos:"n.", def:"a natural tendency", ex:"His proclivity for risk worried investors."},
  {word:"Propitiate", pos:"v.", def:"to appease", ex:"They offered gifts to propitiate the gods."},
  {word:"Quiescent", pos:"adj.", def:"in a state of rest; inactive", ex:"The volcano lay quiescent for decades."},
  {word:"Raucous", pos:"adj.", def:"loud and disorderly", ex:"The raucous party drew complaints."},
  {word:"Recalcitrance", pos:"n.", def:"stubborn resistance", ex:"His recalcitrance delayed the project."},
  {word:"Redolent", pos:"adj.", def:"strongly reminiscent or fragrant", ex:"The air was redolent of pine."},
  {word:"Sagacious", pos:"adj.", def:"wise; discerning", ex:"The sagacious elder advised patience."},
  {word:"Salubrious", pos:"adj.", def:"health-giving", ex:"The salubrious climate aided recovery."},
  {word:"Sanguinary", pos:"adj.", def:"bloodthirsty; bloody", ex:"The sanguinary tale horrified readers."},
  {word:"Solvent", pos:"adj.", def:"able to pay debts", ex:"The firm remained solvent through the downturn."},
  {word:"Surreptitious", pos:"adj.", def:"secret; stealthy", ex:"He took a surreptitious glance at the grade."},
  {word:"Unctuous", pos:"adj.", def:"excessively flattering; oily", ex:"The unctuous salesman repelled her."},
  {word:"Undergird", pos:"v.", def:"to strengthen; support", ex:"Data undergird the theory."},
  {word:"Vapid", pos:"adj.", def:"lacking spirit; dull", ex:"The vapid conversation bored her."},
  {word:"Verisimilitude", pos:"n.", def:"appearance of truth", ex:"The novel's verisimilitude impressed critics."},
  {word:"Vexation", pos:"n.", def:"the state of being annoyed", ex:"To his vexation, the train was late."},
  {word:"Vilification", pos:"n.", def:"slander; defamation", ex:"The vilification backfired on its author."},
  {word:"Withering", pos:"adj.", def:"scornful; destructive", ex:"She gave a withering look."},
  {word:"Zealot", pos:"n.", def:"a fanatical believer", ex:"The zealot would not compromise."},
  {word:"Abjure", pos:"v.", def:"to renounce or reject solemnly", ex:"He abjured his former beliefs."},
  {word:"Acumen", pos:"n.", def:"keen insight; sharp judgment", ex:"Her business acumen built the company."},
  {word:"Adumbrate", pos:"v.", def:"to outline sketchily; foreshadow", ex:"The report adumbrates future risks."},
  {word:"Aggrandize", pos:"v.", def:"to increase power/wealth of", ex:"The king sought to aggrandize his realm."},
  {word:"Anodyne", pos:"adj.", def:"inoffensive; soothing", ex:"An anodyne speech avoided controversy."},
  {word:"Apothegm", pos:"n.", def:"a terse, witty saying", ex:"His apothegms were often quoted."},
  {word:"Arrogate", pos:"v.", def:"to claim without right", ex:"He arrogated authority he did not have."},
  {word:"Assiduous", pos:"adj.", def:"diligent; persevering", ex:"Assiduous study yielded top marks."},
  {word:"Aver", pos:"v.", def:"to state positively; assert", ex:"She averred her innocence."},
  {word:"Bombast", pos:"n.", def:"pompous, empty talk", ex:"The speech was full of bombast."},
  {word:"Cabal", pos:"n.", def:"a secret faction", ex:"A cabal plotted behind closed doors."},
  {word:"Cajole", pos:"v.", def:"to persuade by flattery", ex:"He cajoled her into agreeing."},
  {word:"Calumny", pos:"n.", def:"a false, malicious accusation", ex:"The calumny ruined his name."},
  {word:"Clamor", pos:"n.", def:"loud, sustained noise; outcry", ex:"The clamor of the crowd grew."},
  {word:"Coalesce", pos:"v.", def:"to unite; fuse into one", ex:"The groups coalesced into a party."},
  {word:"Conflagration", pos:"n.", def:"a large, destructive fire", ex:"The conflagration razed the town."},
  {word:"Connive", pos:"v.", def:"to conspire; cooperate secretly in wrongdoing", ex:"They connived to hide the loss."},
  {word:"Corroborate", pos:"v.", def:"to confirm; support with evidence", ex:"Witnesses corroborated his story."},
  {word:"Debunk", pos:"v.", def:"to expose as false", ex:"The study debunked the myth."},
  {word:"Definitive", pos:"adj.", def:"decisive; authoritative", ex:"A definitive edition of the text."},
  {word:"Delineate", pos:"v.", def:"to describe precisely", ex:"The map delineates the border."},
  {word:"Denigrate", pos:"v.", def:"to belittle; speak ill of", ex:"Critics denigrated the novel."},
  {word:"Desultory", pos:"adj.", def:"aimless; jumping haphazardly", ex:"A desultory conversation wandered."},
  {word:"Disabuse", pos:"v.", def:"to free from a false idea", ex:"She disabused him of the notion."},
  {word:"Discreet", pos:"adj.", def:"prudent; careful in conduct", ex:"A discreet inquiry avoided scandal."},
  {word:"Disingenuous", pos:"adj.", def:"not candid; deceptive", ex:"His disingenuous apology rang false."},
  {word:"Effrontery", pos:"n.", def:"shameless boldness", ex:"He had the effrontery to laugh."},
  {word:"Enigmatic", pos:"adj.", def:"mysterious; puzzling", ex:"An enigmatic smile gave nothing away."},
  {word:"Eschew", pos:"v.", def:"to avoid; shun", ex:"He eschewed all luxury."},
  {word:"Evanescent", pos:"adj.", def:"fleeting; vanishing quickly", ex:"Evanescent beauty of a sunset."},
  {word:"Extant", pos:"adj.", def:"still existing", ex:"Few extant copies remain."},
  {word:"Extirpate", pos:"v.", def:"to root out; destroy entirely", ex:"The program extirpated the pest."},
  {word:"Fecund", pos:"adj.", def:"fertile; productive", ex:"Fecund soil yielded crops."},
  {word:"Flagrant", pos:"adj.", def:"openly scandalous", ex:"A flagrant violation of the rules."},
  {word:"Forestall", pos:"v.", def:"to prevent by acting first", ex:"They forestalled the protest."},
  {word:"Fulminate", pos:"v.", def:"to thunder; vehemently protest", ex:"He fulminated against the law."},
  {word:"Gauche", pos:"adj.", def:"awkward; lacking social grace", ex:"His gauche joke offended her."},
  {word:"Grandiloquent", pos:"adj.", def:"pompous in speech", ex:"A grandiloquent address bored all."},
  {word:"Hegemony", pos:"n.", def:"dominance of one group", ex:"Economic hegemony shaped trade."},
  {word:"Hirsute", pos:"adj.", def:"hairy", ex:"The hirsute actor needed grooming."},
  {word:"Histrionic", pos:"adj.", def:"overly theatrical", ex:"Histrionic sobs seemed fake."},
  {word:"Idiosyncratic", pos:"adj.", def:"peculiar to an individual", ex:"His idiosyncratic style divided critics."},
  {word:"Immaculate", pos:"adj.", def:"spotlessly clean; flawless", ex:"An immaculate record."},
  {word:"Imminent", pos:"adj.", def:"about to happen", ex:"Imminent danger approached."},
  {word:"Implacable", pos:"adj.", def:"unable to be appeased", ex:"An implacable foe."},
  {word:"Ineluctable", pos:"adj.", def:"inevitable; unavoidable", ex:"The ineluctable march of time."},
  {word:"Inimical", pos:"adj.", def:"hostile; harmful", ex:"Policies inimical to growth."},
  {word:"Lapidary", pos:"adj.", def:"elegantly concise (of writing)", ex:"Lapidary prose."},
  {word:"Lethargic", pos:"adj.", def:"sluggish; drowsy", ex:"A lethargic response."},
  {word:"Malinger", pos:"v.", def:"to feign illness to avoid duty", ex:"He malingered to skip work."},
  {word:"Metamorphosis", pos:"n.", def:"a transformation", ex:"A caterpillar's metamorphosis."},
  {word:"Mettlesome", pos:"adj.", def:"spirited; courageous", ex:"A mettlesome horse."},
  {word:"Mulish", pos:"adj.", def:"stubborn as a mule", ex:"A mulish refusal."},
  {word:"Nefarious", pos:"adj.", def:"wicked; villainous", ex:"A nefarious scheme."},
  {word:"Nugatory", pos:"adj.", def:"trifling; invalid", ex:"A nugatory objection."},
  {word:"Opprobrium", pos:"n.", def:"public disgrace", ex:"He faced opprobrium for the leak."},
  {word:"Ostracize", pos:"v.", def:"to exclude from a group", ex:"They ostracized the whistleblower."},
  {word:"Palliate", pos:"v.", def:"to lessen severity (not cure)", ex:"Drugs palliate the symptoms."},
  {word:"Panacea", pos:"n.", def:"a cure-all", ex:"No panacea for the crisis."},
  {word:"Peremptory", pos:"adj.", def:"imperious; allowing no contradiction", ex:"A peremptory order."},
  {word:"Perfidy", pos:"n.", def:"treachery; betrayal", ex:"An act of perfidy."},
  {word:"Perfunctory", pos:"adj.", def:"done carelessly; routine", ex:"A perfunctory greeting."},
  {word:"Petrous", pos:"adj.", def:"hard as stone", ex:"Petrous bone."},
  {word:"Pithy", pos:"adj.", def:"concise and forceful", ex:"A pithy remark."},
  {word:"Polemical", pos:"adj.", def:"controversial; argumentative", ex:"A polemical essay."},
  {word:"Prescient", pos:"adj.", def:"having foresight", ex:"A prescient warning."},
  {word:"Probity", pos:"n.", def:"integrity; uprightness", ex:"A judge of great probity."},
  {word:"Profligate", pos:"adj.", def:"recklessly wasteful", ex:"Profligate spending."},
  {word:"Propitious", pos:"adj.", def:"favorable", ex:"A propitious moment."},
  {word:"Prosaic", pos:"adj.", def:"dull; ordinary", ex:"A prosaic life."},
  {word:"Punctilious", pos:"adj.", def:"precise about details", ex:"A punctilious editor."},
  {word:"Pusillanimous", pos:"adj.", def:"cowardly", ex:"A pusillanimous retreat."},
  {word:"Raconteur", pos:"n.", def:"a skilled storyteller", ex:"A witty raconteur."},
  {word:"Rapacious", pos:"adj.", def:"greedy; predatory", ex:"Rapacious developers."},
  {word:"Refulgent", pos:"adj.", def:"shining brightly", ex:"A refulgent dawn."},
  {word:"Scintillating", pos:"adj.", def:"brilliantly lively", ex:"A scintillating conversation."},
  {word:"Sedulous", pos:"adj.", def:"diligent; persevering", ex:"Sedulous effort."},
  {word:"Spartan", pos:"adj.", def:"austere; frugal", ex:"A spartan room."},
  {word:"Spurious", pos:"adj.", def:"false; counterfeit", ex:"A spurious claim."},
  {word:"Stolid", pos:"adj.", def:"unemotional; impassive", ex:"A stolid face."},
  {word:"Sycophant", pos:"n.", def:"a fawning flatterer", ex:"A sycophant praised the boss."},
  {word:"Truculent", pos:"adj.", def:"aggressively defiant", ex:"A truculent tone."},
  {word:"Umbrage", pos:"n.", def:"offense; resentment", ex:"He took umbrage at the joke."},
  {word:"Vituperate", pos:"v.", def:"to berate abusively", ex:"She vituperated the committee."},
  {word:"Winnow", pos:"v.", def:"to separate chaff; sift", ex:"Winnow the facts from rumor."},
  {word:"Variegated", pos:"adj.", def:"varied; multicolored", ex:"Variegated foliage."},
  {word:"Voracious", pos:"adj.", def:"ravenously eager", ex:"A voracious reader."},
  {word:"Yoke", pos:"n.", def:"a burden; bond", ex:"The yoke of debt."},
  {word:"Zephyr", pos:"n.", def:"a gentle breeze", ex:"A warm zephyr."}
];
